### ISSUE TITLE
.md文件支持直接引入.vue文件吗？

### ISSUE THREAD

**Issue by yc910920** [xinlei3166/vitepress-demo#2]
现在.md文件里的示例都是写在```vue   ``` 之间，是否支持直接引入vue文件呢？

**Comment by xinlei3166** [comment]
支持的, 这有个例子: https://github.com/xinlei3166/vitepress-demo/blob/master/docs/components/vue.md .

**Comment by xinlei3166** [comment]
> 现在.md文件里的示例都是写在`vue ` 之间，是否支持直接引入vue文件呢？

支持的, 这有个例子: https://github.com/xinlei3166/vitepress-demo/blob/master/docs/components/vue.md .

**Comment by yc910920** [comment]
> > 现在.md文件里的示例都是写在`vue ` 之间，是否支持直接引入vue文件呢？
> 
> 支持的, 这有个例子: https://github.com/xinlei3166/vitepress-demo/blob/master/docs/components/vue.md .

谢谢，再问一下，直接引入vue文件的话，目前是没有显示代码这块的吗？

**Comment by xinlei3166** [comment]
> > > 现在.md文件里的示例都是写在`vue ` 之间，是否支持直接引入vue文件呢？
> > 
> > 
> > 支持的, 这有个例子: https://github.com/xinlei3166/vitepress-demo/blob/master/docs/components/vue.md .
> 
> 谢谢，再问一下，直接引入vue文件的话，目前是没有显示代码这块的吗？

代码块需要单独写一份。
例如：
上面是组件
`<demo-block>
  <xl-button>默认按钮</xl-button>
  <xl-button type="primary">主要按钮</xl-button>
</demo-block>`

下面是代码，就按正常的markdown高亮代码的方式写一段代码就行。
```vue
<xl-button>默认按钮</xl-button>
<xl-button type="primary">主要按钮</xl-button>
```

**Comment by yc910920** [comment]
> > > > 现在.md文件里的示例都是写在`vue ` 之间，是否支持直接引入vue文件呢？
> > > 
> > > 
> > > 支持的, 这有个例子: https://github.com/xinlei3166/vitepress-demo/blob/master/docs/components/vue.md .
> > 
> > 
> > 谢谢，再问一下，直接引入vue文件的话，目前是没有显示代码这块的吗？
> 
> 代码块需要单独写一份。
> 例如：
> 上面是组件
> `<demo-block> <xl-button>默认按钮</xl-button> <xl-button type="primary">主要按钮</xl-button> </demo-block>`
> 
> 下面是代码，就按正常的markdown高亮代码的方式写一段代码就行。
> 
> ```
> <xl-button>默认按钮</xl-button>
> <xl-button type="primary">主要按钮</xl-button>
> ```

你好，我想问下组件库是否支持显示<scritp></script>里的内容类似这种

**Comment by yc910920** [comment]
请问现在文档是否可以支持<script></script>标签的展示？
