### ISSUE TITLE
请问 如何现在复杂的组件展示，比如带有js和css的组件展示

### ISSUE THREAD

**Issue by lyh0371** [xinlei3166/vitepress-demo#3]
```vue
<xl-button @click=“handle”>默认按钮</xl-button>
<script>
export defsult {
setup(){
const handle = ()=>{ todo... }

return {
handle
}
}
}

</script>
```

**Comment by yc910920** [comment]
同问是否支持这种形式

**Comment by xinlei3166** [comment]
可以的，与平时写vue一样的。

页面demo： 
https://xinlei3166.github.io/vitepress-demo/components/vue-script.html 

源码参考：
https://github.com/xinlei3166/vitepress-demo/blob/master/docs/components/vue-script.md 
https://github.com/xinlei3166/vitepress-demo/blob/master/docs/.vitepress/components/input/demo.vue

**Comment by xinlei3166** [comment]
hello, 你期望的需求，我已经实现。

https://xinlei3166.github.io/vitepress-demo/components/vue-script.html

![image](https://user-images.githubusercontent.com/22881872/123773642-65233b80-d8ff-11eb-9650-00bed202f97e.png)
